from distutils.core import setup

setup(
    name='Tracktime',
    version='0.1',
    packages=['src.models.participants', 'venv.lib.python3.5.distutils', 'venv.lib.python3.5.encodings',
              'venv.lib.python3.5.importlib', 'venv.lib.python3.5.collections', 'venv.lib.python3.5.site-packages.pip',
              'venv.lib.python3.5.site-packages.pip.req', 'venv.lib.python3.5.site-packages.pip.vcs',
              'venv.lib.python3.5.site-packages.pip.utils', 'venv.lib.python3.5.site-packages.pip.compat',
              'venv.lib.python3.5.site-packages.pip.models', 'venv.lib.python3.5.site-packages.pip._vendor',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.serializer',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor._markerlib',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.xlrd', 'venv.lib.python3.5.site-packages.click',
              'venv.lib.python3.5.site-packages.flask', 'venv.lib.python3.5.site-packages.flask.ext',
              'venv.lib.python3.5.site-packages.wheel', 'venv.lib.python3.5.site-packages.wheel.test',
              'venv.lib.python3.5.site-packages.wheel.test.simple.dist.simpledist',
              'venv.lib.python3.5.site-packages.wheel.test.complex-dist.complexdist',
              'venv.lib.python3.5.site-packages.wheel.tool', 'venv.lib.python3.5.site-packages.wheel.signatures',
              'venv.lib.python3.5.site-packages.jinja2', 'venv.lib.python3.5.site-packages.wtforms',
              'venv.lib.python3.5.site-packages.wtforms.ext', 'venv.lib.python3.5.site-packages.wtforms.ext.csrf',
              'venv.lib.python3.5.site-packages.wtforms.ext.i18n',
              'venv.lib.python3.5.site-packages.wtforms.ext.django',
              'venv.lib.python3.5.site-packages.wtforms.ext.django.templatetags',
              'venv.lib.python3.5.site-packages.wtforms.ext.dateutil',
              'venv.lib.python3.5.site-packages.wtforms.ext.appengine',
              'venv.lib.python3.5.site-packages.wtforms.ext.sqlalchemy',
              'venv.lib.python3.5.site-packages.wtforms.csrf', 'venv.lib.python3.5.site-packages.wtforms.fields',
              'venv.lib.python3.5.site-packages.wtforms.widgets', 'venv.lib.python3.5.site-packages.werkzeug',
              'venv.lib.python3.5.site-packages.werkzeug.debug', 'venv.lib.python3.5.site-packages.werkzeug.contrib',
              'venv.lib.python3.5.site-packages.flask_wtf', 'venv.lib.python3.5.site-packages.flask_wtf.recaptcha',
              'venv.lib.python3.5.site-packages._markerlib', 'venv.lib.python3.5.site-packages.markupsafe',
              'venv.lib.python3.5.site-packages.setuptools', 'venv.lib.python3.5.site-packages.setuptools.command',
              'venv.lib.python3.5.site-packages.sqlalchemy', 'venv.lib.python3.5.site-packages.sqlalchemy.ext',
              'venv.lib.python3.5.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.5.site-packages.sqlalchemy.orm', 'venv.lib.python3.5.site-packages.sqlalchemy.sql',
              'venv.lib.python3.5.site-packages.sqlalchemy.util', 'venv.lib.python3.5.site-packages.sqlalchemy.event',
              'venv.lib.python3.5.site-packages.sqlalchemy.engine',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.5.site-packages.sqlalchemy.databases',
              'venv.lib.python3.5.site-packages.sqlalchemy.connectors',
              'venv.lib.python3.5.site-packages.pkg_resources',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.5.site-packages.flask_sqlalchemy'],
    url='',
    license='MIT',
    author='ferojanus',
    author_email='inbox.jfblg@gmail.com',
    description='Flask based web app for time management during an small athletic event.'
)
